// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using sistema_eventos.Db;

#nullable disable

namespace sistema_eventos.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20240811021649_TicketsCreatTable")]
    partial class TicketsCreatTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("sistema_eventos.Models.CadeiraEventoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("cadeira_id")
                        .HasColumnType("integer");

                    b.Property<int>("evento_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("cadeira_id");

                    b.HasIndex("evento_id");

                    b.ToTable("cadeiras_eventos");
                });

            modelBuilder.Entity("sistema_eventos.Models.CadeiraModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("cadeira")
                        .HasColumnType("integer");

                    b.Property<string>("fila")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("cadeiras");
                });

            modelBuilder.Entity("sistema_eventos.Models.EventosModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("data_hora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("preco")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("eventos");
                });

            modelBuilder.Entity("sistema_eventos.Models.TicketsModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("cadeiras_eventos_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("data_compra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("tickets_codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("cadeiras_eventos_id");

                    b.HasIndex("user_id");

                    b.ToTable("tickets");
                });

            modelBuilder.Entity("sistema_eventos.Models.UserModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("tipo_user")
                        .HasColumnType("integer");

                    b.Property<string>("token")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("sistema_eventos.Models.CadeiraEventoModel", b =>
                {
                    b.HasOne("sistema_eventos.Models.CadeiraModel", "cadeiras")
                        .WithMany("CadeiraEvento")
                        .HasForeignKey("cadeira_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistema_eventos.Models.EventosModel", "eventos")
                        .WithMany("CadeiraEvento")
                        .HasForeignKey("evento_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cadeiras");

                    b.Navigation("eventos");
                });

            modelBuilder.Entity("sistema_eventos.Models.TicketsModel", b =>
                {
                    b.HasOne("sistema_eventos.Models.CadeiraEventoModel", "CadeiraEvento")
                        .WithMany("Tickets")
                        .HasForeignKey("cadeiras_eventos_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistema_eventos.Models.UserModel", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CadeiraEvento");

                    b.Navigation("User");
                });

            modelBuilder.Entity("sistema_eventos.Models.CadeiraEventoModel", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("sistema_eventos.Models.CadeiraModel", b =>
                {
                    b.Navigation("CadeiraEvento");
                });

            modelBuilder.Entity("sistema_eventos.Models.EventosModel", b =>
                {
                    b.Navigation("CadeiraEvento");
                });

            modelBuilder.Entity("sistema_eventos.Models.UserModel", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
